### ISSUE TITLE
APK download

### ISSUE THREAD

**Issue by IzzySoft** [5AbhishekSaxena/GermanPocketDictionary#28]
Would you consider making the APK available outside Google's walled garden, so users without PlayStore access can use it? Best place would be attaching the APKs to their corresponding [releases](https://github.com/5AbhishekSaxena/GermanPocketDictionary/releases), starting with the recent one. Thanks in advance!

**Comment by IzzySoft** [comment]
Any chance, @5AbhishekSaxena ?

**Comment by 5AbhishekSaxena** [comment]
No, sorry. Currently I don't have any plans of putting the apk with the releases.

**Comment by IzzySoft** [comment]
Sad. So those of us who cannot access PlayStore cannot use your app then. But OK, I of course accept your decision.
