### ISSUE TITLE
Feature request : Add "Numbers" tab 

### ISSUE THREAD

**Issue by bhoomigadhiya** [5AbhishekSaxena/GermanPocketDictionary#34]
Add the "Number" tab separately which shows numbers only. This app has the numbers but it is in "All Words". It would be easy to read if there is separate tab for numbers.

**Comment by 5AbhishekSaxena** [comment]
Thanks for raising the issue. There is supposed to be a separate tab for numbers. I missed it adding it to the list of tabs.
